Keyboard.press('T');
Keyboard.press('h');
Keyboard.press('e');
Keyboard.press(' ');
Keyboard.press('q');
Keyboard.press('u');
Keyboard.press('i');
Keyboard.press('c');
Keyboard.press('k');
Keyboard.press(' ');
Keyboard.press('b');
Keyboard.press('r');
Keyboard.press('o');
Keyboard.press('w');
Keyboard.press('n');
Keyboard.press(' ');
Keyboard.press('f');
Keyboard.press('o');
Keyboard.press('x');
Keyboard.press(' ');
Keyboard.press('j');
Keyboard.press('u');
Keyboard.press('m');
Keyboard.press('p');
Keyboard.press('s');
Keyboard.press(' ');
Keyboard.press('o');
Keyboard.press('v');
Keyboard.press('e');
Keyboard.press('r');
Keyboard.press(' ');
Keyboard.press('t');
Keyboard.press('h');
Keyboard.press('e');
Keyboard.press(' ');
Keyboard.press('l');
Keyboard.press('a');
Keyboard.press('z');
Keyboard.press('y');
Keyboard.press(' ');
Keyboard.press('d');
Keyboard.press('o');
Keyboard.press('g');
Keyboard.press(46); // 46 is the ASCII code for '.'